import "oaidl.idl";
import "ocidl.idl";
import "..\fbe.idl";

[
	uuid(B963BA28-01AA-40C2-8EF7-9F89D47C2F66),
]
library ExportHTMLLib
{
	importlib("stdole2.tlb");
	[
		uuid(E242A6D3-84BF-4285-9FAA-160F95370668)
	]
	coclass ExportHTMLPlugin
	{
		[default] interface IFBEExportPlugin;
	};
};