#pragma once

struct VB_ERRORS
{
	HRESULT Error;
	CString Source;
	CString Description;
};

// currently supported dictionaries
const VB_ERRORS vberrs[] = { 
	{(HRESULT)0x800A03E9, L"Microsoft VBScript syntax error",  L"Memory error"},
	{(HRESULT)0x800A03EA, L"Microsoft VBScript syntax error",  L"Syntax error"},
	{(HRESULT)0x800A03EB, L"Microsoft VBScript syntax error",  L"Lack of ':'"},
	{(HRESULT)0x800A03ED, L"Microsoft VBScript syntax error",  L"Lack of '('"},
	{(HRESULT)0x800A03EE, L"Microsoft VBScript syntax error",  L"Lack of ')'"},
	{(HRESULT)0x800A03EF, L"Microsoft VBScript syntax error",  L"Lack of ']'"},
	{(HRESULT)0x800A03F2, L"Microsoft VBScript syntax error",  L"The lack of identifiers"},
	{(HRESULT)0x800A03F3, L"Microsoft VBScript syntax error",  L"Lack of '='"},
	{(HRESULT)0x800A03F4, L"Microsoft VBScript syntax error",  L"Lack of 'If'"},
	{(HRESULT)0x800A03F5, L"Microsoft VBScript syntax error",  L"Lack of 'To'"},
	{(HRESULT)0x800A03F6, L"Microsoft VBScript syntax error",  L"Lack of 'End'"},
	{(HRESULT)0x800A03F7, L"Microsoft VBScript syntax error",  L"Lack of 'Function'"},
	{(HRESULT)0x800A03F8, L"Microsoft VBScript syntax error",  L"Lack of 'Sub'"},
	{(HRESULT)0x800A03F9, L"Microsoft VBScript syntax error",  L"Lack of 'Then'"},
	{(HRESULT)0x800A03FA, L"Microsoft VBScript syntax error",  L"Lack of 'Wend'"},
	{(HRESULT)0x800A03FB, L"Microsoft VBScript syntax error",  L"Lack of 'Loop'"},
	{(HRESULT)0x800A03FC, L"Microsoft VBScript syntax error",  L"Lack of 'Next'"},
	{(HRESULT)0x800A03FD, L"Microsoft VBScript syntax error",  L"Lack of 'Case'"},
	{(HRESULT)0x800A03FE, L"Microsoft VBScript syntax error",  L"Lack of 'Select'"},
	{(HRESULT)0x800A03FF, L"Microsoft VBScript syntax error",  L"The lack of expression"},
	{(HRESULT)0x800A0400, L"Microsoft VBScript syntax error",  L"The lack of statement"},
	{(HRESULT)0x800A0401, L"Microsoft VBScript syntax error",  L"Statement is not the end of"},
	{(HRESULT)0x800A0402, L"Microsoft VBScript syntax error",  L"The lack of integer constants"},
	{(HRESULT)0x800A0403, L"Microsoft VBScript syntax error",  L"Lack of 'While ' or 'Until'"},
	{(HRESULT)0x800A0404, L"Microsoft VBScript syntax error",  L"Lack of 'While ', 'Until' or end of statement is not"},
	{(HRESULT)0x800A0405, L"Microsoft VBScript syntax error",  L"Lack of 'With'"},
	{(HRESULT)0x800A0406, L"Microsoft VBScript syntax error",  L"Identifier is too long"},
	{(HRESULT)0x800A0407, L"Microsoft VBScript syntax error",  L"Invalid digital"},
	{(HRESULT)0x800A0408, L"Microsoft VBScript syntax error",  L"Invalid character"},
	{(HRESULT)0x800A0409, L"Microsoft VBScript syntax error",  L"Not the end of the string constant"},
	{(HRESULT)0x800A040A, L"Microsoft VBScript syntax error",  L"Notes is not the end of"},
	{(HRESULT)0x800A040D, L"Microsoft VBScript syntax error",  L"Invalid use of 'Me' keyword"},
	{(HRESULT)0x800A040E, L"Microsoft VBScript syntax error",  L"'Loop' statement the lack of 'do'"},
	{(HRESULT)0x800A040F, L"Microsoft VBScript syntax error",  L"Invalid 'exit' statement"},
	{(HRESULT)0x800A0410, L"Microsoft VBScript syntax error",  L"Cycle control variable 'for' null and void"},
	{(HRESULT)0x800A0411, L"Microsoft VBScript syntax error",  L"The name of re-definition of"},
	{(HRESULT)0x800A0412, L"Microsoft VBScript syntax error",  L"Must be the first in a line statement"},
	{(HRESULT)0x800A0413, L"Microsoft VBScript syntax error",  L"Can not assign non-ByVal parameters"},
	{(HRESULT)0x800A0414, L"Microsoft VBScript syntax error",  L"Call the subro utine can not use brackets when"},
	{(HRESULT)0x800A0415, L"Microsoft VBScript syntax error",  L"The lack of te xt constants"},
	{(HRESULT)0x800A0416, L"Microsoft VBScript syntax error",  L"Lack of 'In'"},
	{(HRESULT)0x800A0417, L"Microsoft VBScript syntax error",  L"Lack of 'Class'"},
	{(HRESULT)0x800A0418, L"Microsoft VBScript syntax error",  L"Must be within the definition of a class"},
	{(HRESULT)0x800A0419, L"Microsoft VBScript syntax error",  L"In the attribu te the lack of a statement Let, Set or Get"},
	{(HRESULT)0x800A041A, L"Microsoft VBScript syntax error",  L"Lack of 'Property'"},
	{(HRESULT)0x800A041B, L"Microsoft VBScript syntax error",  L"All of the properties in the specification, the number of variables must be consistent"},
	{(HRESULT)0x800A041C, L"Microsoft VBScript syntax error",  L"In a category does not allow a number of default attributes / methods"},
	{(HRESULT)0x800A041D, L"Microsoft VBScript syntax error",  L"Class did not initialize or terminate the process parameters"},
	{(HRESULT)0x800A041E, L"Microsoft VBScript syntax error",  L"Attribute set or let must have at least one parameter"},
	{(HRESULT)0x800A041F, L"Microsoft VBScript syntax error",  L"Error 'Next'"},
	{(HRESULT)0x800A0420, L"Microsoft VBScript syntax error",  L"Default 'can only be in the 'Property', 'Function' or 'Sub' in the designated"},
	{(HRESULT)0x800A0421, L"Microsoft VBScript syntax error",  L"Specify 'Default' must be specified when the 'Public'"},
	{(HRESULT)0x800A0422, L"Microsoft VBScript syntax error",  L"Can only specify the Property Get in the 'Default'"},
	{(HRESULT)0x800A0005, L"Microsoft VBScript runtime error", L"Invalid procedure call or parameter"},
	{(HRESULT)0x800A0006, L"Microsoft VBScript runtime error", L"Overflow error"},
	{(HRESULT)0x800A0007, L"Microsoft VBScript runtime error", L"Memory error"},
	{(HRESULT)0x800A0009, L"Microsoft VBScript runtime error", L"Subscript cross-border"},
	{(HRESULT)0x800A000A, L"Microsoft VBScript runtime error", L"The array as a fixed-length or temporary locked"},
	{(HRESULT)0x800A000B, L"Microsoft VBScript runtime error", L"Division by zero"},
	{(HRESULT)0x800A000D, L"Microsoft VBScript runtime error", L"Type does not match"},
	{(HRESULT)0x800A000E, L"Microsoft VBScript runtime error", L"String have not enough space"},
	{(HRESULT)0x800A0011, L"Microsoft VBScript runtime error", L"Unable to perform the required operation"},
	{(HRESULT)0x800A001C, L"Microsoft VBScript runtime error", L"Stack overflow"},
	{(HRESULT)0x800A0023, L"Microsoft VBScript runtime error", L"Undefined procedure or function"},
	{(HRESULT)0x800A0030, L"Microsoft VBScript runtime error", L"Load DLL Error"},
	{(HRESULT)0x800A0033, L"Microsoft VBScript runtime error", L"Internal Error"},
	{(HRESULT)0x800A0034, L"Microsoft VBScript runtime error", L"Wrong file name or number"},
	{(HRESULT)0x800A0035, L"Microsoft VBScript runtime error", L"File Not Found"},
	{(HRESULT)0x800A0036, L"Microsoft VBScript runtime error", L"Wrong file mode"},
	{(HRESULT)0x800A0037, L"Microsoft VBScript runtime error", L"Document has been opened"},
	{(HRESULT)0x800A0039, L"Microsoft VBScript runtime error", L"Device I/O error"},
	{(HRESULT)0x800A003A, L"Microsoft VBScript runtime error", L"File already exists"},
	{(HRESULT)0x800A003D, L"Microsoft VBScript runtime error", L"Disk full"},
	{(HRESULT)0x800A003E, L"Microsoft VBScript runtime error", L"Input file beyond the end of"},
	{(HRESULT)0x800A0043, L"Microsoft VBScript runtime error", L"Too many files"},
	{(HRESULT)0x800A0044, L"Microsoft VBScript runtime error", L"Device not available"},
	{(HRESULT)0x800A0046, L"Microsoft VBScript runtime error", L"Do not have permission to"},
	{(HRESULT)0x800A0047, L"Microsoft VBScript runtime error", L"Disk not ready"},
	{(HRESULT)0x800A004A, L"Microsoft VBScript runtime error", L"Can not rename a symbol of other drive"},
	{(HRESULT)0x800A004B, L"Microsoft VBScript runtime error", L"Path/file access error"},
	{(HRESULT)0x800A004C, L"Microsoft VBScript runtime error", L"Path not found"},
	{(HRESULT)0x800A005B, L"Microsoft VBScript runtime error", L"Object variable not set"},
	{(HRESULT)0x800A005C, L"Microsoft VBScript runtime error", L"For cycle unini tialized"},
	{(HRESULT)0x800A005E, L"Microsoft VBScript runtime error", L"Invalid use of Null"},
	{(HRESULT)0x800A0142, L"Microsoft VBScript runtime error", L"Can not create necessary temporary file"},
	{(HRESULT)0x800A01A8, L"Microsoft VBScript runtime error", L"The lack of target"},
	{(HRESULT)0x800A01AD, L"Microsoft VBScript runtime error", L"ActiveX component can not create object"},
	{(HRESULT)0x800A01AE, L"Microsoft VBScript runtime error", L"Type of operation can not support Automation"},
	{(HRESULT)0x800A01B0, L"Microsoft VBScript runtime error", L"Automation oper ations in the file name or class name not found"},
	{(HRESULT)0x800A01B6, L"Microsoft VBScript runtime error", L"The object does not support this property or method"},
	{(HRESULT)0x800A01B8, L"Microsoft VBScript runtime error", L"Automation error"},
	{(HRESULT)0x800A01BD, L"Microsoft VBScript runtime error", L"The object does not support this operation"},
	{(HRESULT)0x800A01BE, L"Microsoft VBScript runtime error", L"The object does not support named parameters"},
	{(HRESULT)0x800A01BF, L"Microsoft VBScript runtime error", L"The object does not support the current regional settings"},
	{(HRESULT)0x800A01C0, L"Microsoft VBScript runtime error", L"Not found has been named parameters"},
	{(HRESULT)0x800A01C1, L"Microsoft VBScript runtime error", L"Parameters are certainly options"},
	{(HRESULT)0x800A01C2, L"Microsoft VBScript runtime error", L"Wrong number of parameters or invalid attribute value of the parameter"},
	{(HRESULT)0x800A01C3, L"Microsoft VBScript runtime error", L"Object is not a collection of"},
	{(HRESULT)0x800A01C5, L"Microsoft VBScript runtime error", L"Did not find the specified DLL function"},
	{(HRESULT)0x800A01C7, L"Microsoft VBScript runtime error", L"Code resource lock error"},
	{(HRESULT)0x800A01CA, L"Microsoft VBScript runtime error", L"Use a variable in VBScript does not support the type of Automation"},
	{(HRESULT)0x800A01CE, L"Microsoft VBScript runtime error", L"Remote server does not exist or is not available"},
	{(HRESULT)0x800A01E1, L"Microsoft VBScript runtime error", L"Invalid image"},
	{(HRESULT)0x800A01F4, L"Microsoft VBScript runtime error", L"Variable not defined"},
	{(HRESULT)0x800A01F5, L"Microsoft VBScript runtime error", L"Illegal assignment"},
	{(HRESULT)0x800A01F6, L"Microsoft VBScript runtime error", L"Object can not be safe for use Script Programming"},
	{(HRESULT)0x800A01F7, L"Microsoft VBScript runtime error", L"Object can not be safe to initialize "},
	{(HRESULT)0x800A01F8, L"Microsoft VBScript runtime error", L"Object can not create a secure environment"},
	{(HRESULT)0x800A01F9, L"Microsoft VBScript runtime error", L"Invalid or non-qualified reference"},
	{(HRESULT)0x800A01FA, L"Microsoft VBScript runtime error", L"Type is not defined"},
	{(HRESULT)0x800A01FB, L"Microsoft VBScript runtime error", L"An unexpected error"},
	{(HRESULT)0x800A1398, L"Microsoft VBScript runtime error", L"The lack of expression of conventional object"},
	{(HRESULT)0x800A1399, L"Microsoft VBScript runtime error", L"Regular expression syntax error"},
	{(HRESULT)0x800A139A, L"Microsoft VBScript runtime error", L"Unexpected quantifier in regular expression"},
	{(HRESULT)0x800A139B, L"Microsoft VBScript runtime error", L"Regular expression is missing ']'"},
	{(HRESULT)0x800A139C, L"Microsoft VBScript runtime error", L"Regular expression is missing ')'"},
	{(HRESULT)0x800A139D, L"Microsoft VBScript runtime error", L"Character set cross-border"},
	{(HRESULT)0x800A802B, L"Microsoft VBScript runtime error", L"Element not found"}
};
